/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
        greetUser("User");
    }
    public String greetUser(String name) {
        return "Hello " + name + " !";
    }
}
